import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Ladino, transcritas de docs/CARD_CATALOG.md.
 *
 * A Brecha é moeda e aparece dentro do custo impresso — "2 AP + consuma 1
 * Brecha". Ela fica sobre o adversário, mas pertence ao Ladino: quem a cria e
 * quem a consome é ele. Brecha não é Condição.
 */
export const HABILIDADES_DO_LADINO: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('L01'),
    classe: 'ladino',
    nome: 'Corte Rápido',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: 'Se for sua primeira Ação, recebe +1 D.',
  },
  {
    id: cardId('L02'),
    classe: 'ladino',
    nome: 'Finta',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 1, impacto: 1 },
    cooldown: 1,
    texto:
      'Se o adversário usar uma carta de Reação, recupere 1 AP. Se não usar e este Ataque causar Dano à Vida, crie 1 Brecha.',
  },
  {
    id: cardId('L03'),
    classe: 'ladino',
    nome: 'Corte Serrilhado',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto: 'Se causar Dano à Vida, aplique Sangramento 1.',
  },
  {
    id: cardId('L04'),
    classe: 'ladino',
    nome: 'Golpe nos Rins',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'brecha', quantidade: 1 } },
    valores: { dano: 2, impacto: 2 },
    cooldown: 2,
    texto: 'Se for sua segunda Ação, recebe +1 D. Se causar Dano à Vida, aplique Sangramento 1.',
  },
  {
    id: cardId('L05'),
    classe: 'ladino',
    nome: 'Estocada Sombria',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'brecha', quantidade: 1 } },
    valores: { dano: 4, impacto: 1 },
    cooldown: 2,
    texto: 'Se for sua primeira Ação e o adversário não usar carta de Reação, recebe +2 D.',
  },
  {
    id: cardId('L06'),
    classe: 'ladino',
    nome: 'Punhalada Oportunista',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 3, impacto: 0 },
    cooldown: 2,
    texto: 'Só pode ser usada contra Guarda 0.',
  },
  {
    id: cardId('L07'),
    classe: 'ladino',
    nome: 'Corte de Tendão',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 2, impacto: 2 },
    cooldown: 2,
    texto: 'Se o adversário já tiver Sangramento, recebe +1 I.',
  },
  {
    id: cardId('L08'),
    classe: 'ladino',
    nome: 'Execução Precisa',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3, variavel: { recurso: 'brecha', minimo: 0, maximo: 3 } },
    valores: { dano: 4, impacto: 1 },
    cooldown: 3,
    texto: 'Ao declarar, consuma até 3 Brechas. Recebe +1 D por Brecha consumida.',
  },
  {
    id: cardId('L09'),
    classe: 'ladino',
    nome: 'Ataque de Desarme',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'brecha', quantidade: 1 } },
    valores: { dano: 3, impacto: 1 },
    cooldown: 3,
    texto: 'Se causar Dano à Vida, escolha uma carta de Reação adversária em CD1 e mova para CD2.',
  },
  {
    id: cardId('L10'),
    classe: 'ladino',
    nome: 'Golpe Final',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'brecha', quantidade: 2 } },
    valores: { dano: 4, impacto: 0 },
    cooldown: 2,
    texto: 'Se for sua terceira Ação, recebe +2 D.',
  },
  {
    id: cardId('L11'),
    classe: 'ladino',
    nome: 'Preparar a Brecha',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 1,
    texto: 'Crie 1 Brecha. Seu próximo Ataque neste turno recebe +1 I.',
  },
  {
    id: cardId('L12'),
    classe: 'ladino',
    nome: 'Marcar o Alvo',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Coloque uma Marca de Golpe sobre o adversário. A próxima vez que um Ataque do Ladino causar Dano à Vida, remova a Marca e cause +2 D. Só pode existir 1 Marca de Golpe.',
  },
  {
    id: cardId('L13'),
    classe: 'ladino',
    nome: 'Sabotagem',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'brecha', quantidade: 1 } },
    cooldown: 3,
    texto:
      'Escolha: mova uma habilidade adversária de CD1 para CD2; ou escolha uma Carta de Classe inimiga Pronta e deixe-a Ativada sem resolver seu efeito.',
  },
  {
    id: cardId('L14'),
    classe: 'ladino',
    nome: 'Passo Falso',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Seu próximo Ataque neste turno recebe +2 D se o adversário usar uma carta de Reação. Se não usar, crie 1 Brecha depois da resolução.',
  },
  {
    id: cardId('L15'),
    classe: 'ladino',
    nome: 'Esquiva',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 3 D. Se o Dano final for 0, crie 1 Brecha.',
  },
  {
    id: cardId('L16'),
    classe: 'ladino',
    nome: 'Adaga de Aparar',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto:
      'Reduza 2 D e 1 I. Se o Dano final for 0, o adversário perde 1 Vida e crie 1 Brecha se ainda houver espaço.',
  },
  {
    id: cardId('L17'),
    classe: 'ladino',
    nome: 'Bomba de Fumaça',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto:
      'Reduza 2 D e 3 I. Efeitos de Cartas de Classe inimigas não podem aumentar esta ação depois que Bomba de Fumaça resolver.',
  },
  {
    id: cardId('L18'),
    classe: 'ladino',
    nome: 'Escapar pelas Sombras',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2, recurso: { recurso: 'brecha', quantidade: 1 } },
    cooldown: 3,
    texto: 'Reduza 4 D. Depois da resolução, devolva uma habilidade sua de CD1 à mão.',
  },
  {
    id: cardId('L19'),
    classe: 'ladino',
    nome: 'Contra-ataque Sujo',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1, recurso: { recurso: 'brecha', quantidade: 1 } },
    cooldown: 2,
    texto: 'Reduza 2 D. Se o Dano final for 0, aplique Sangramento 1 ao adversário.',
  },
  {
    id: cardId('L20'),
    classe: 'ladino',
    nome: 'Instinto de Sobrevivência',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2, recurso: { recurso: 'brecha', quantidade: 2 } },
    cooldown: 3,
    texto: 'Só contra um Ataque que reduziria sua Vida a 0. Reduza 5 D.',
  },
];
