import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Bardo, transcritas de docs/CARD_CATALOG.md.
 *
 * A Nota é dado impresso como qualquer outro: ela vem do catálogo e não de
 * quem joga. As duas exceções estão no próprio texto — o Improviso, que manda
 * escolher a Nota ao jogar, e as Reações, que não têm Nota nenhuma, porque
 * Cadência é coisa de Ações consecutivas do próprio turno.
 */
export const HABILIDADES_DO_BARDO: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('B01'),
    classe: 'bardo',
    nome: 'Batida Marcial',
    tipo: 'ataque',
    tags: [],
    nota: 'pulso',
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: 'Se for sua primeira Ação, recebe +1 I.',
  },
  {
    id: cardId('B02'),
    classe: 'bardo',
    nome: 'Corda Cortante',
    tipo: 'ataque',
    tags: [],
    nota: 'melodia',
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 1,
    texto: 'Se a Ação imediatamente anterior foi Pulso, recebe +1 D.',
  },
  {
    id: cardId('B03'),
    classe: 'bardo',
    nome: 'Acorde Estridente',
    tipo: 'ataque',
    tags: [],
    nota: 'harmonia',
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 2 },
    cooldown: 2,
    texto:
      'Só recebe o bônus se você já produziu Cadência neste turno. Se a Ação anterior foi Melodia, recebe +1 I.',
  },
  {
    id: cardId('B04'),
    classe: 'bardo',
    nome: 'Crescendo',
    tipo: 'ataque',
    tags: [],
    nota: 'pulso',
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 4, impacto: 2 },
    cooldown: 2,
    texto: 'Recebe +1 D por Nota diferente usada anteriormente neste turno, máximo +2 D.',
  },
  {
    id: cardId('B05'),
    classe: 'bardo',
    nome: 'Nota Perfurante',
    tipo: 'ataque',
    tags: [],
    nota: 'melodia',
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 2, impacto: 3 },
    cooldown: 2,
    texto: 'Se causar Ruptura, sua próxima Ação neste turno custa 1 AP a menos, mínimo 1.',
  },
  {
    id: cardId('B06'),
    classe: 'bardo',
    nome: 'Refrão Cortante',
    tipo: 'ataque',
    tags: [],
    nota: 'harmonia',
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 3, impacto: 0 },
    cooldown: 2,
    texto:
      'Só pode ser usado se você já produziu Cadência neste turno. Se for sua terceira Ação, recebe +1 D.',
  },
  {
    id: cardId('B07'),
    classe: 'bardo',
    nome: 'Dissonância',
    tipo: 'ataque',
    tags: [],
    nota: 'harmonia',
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto:
      'Se o adversário usar uma carta de Reação e este Ataque ainda causar Dano à Vida, sua próxima Ação neste turno recebe +1 D ou +1 I se for Ataque.',
  },
  {
    id: cardId('B08'),
    classe: 'bardo',
    nome: 'Pancada de Compasso',
    tipo: 'ataque',
    tags: [],
    nota: 'pulso',
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 2 },
    cooldown: 2,
    texto: 'Se o adversário estiver com Reserva 0 ao declarar, recebe +1 D.',
  },
  {
    id: cardId('B09'),
    classe: 'bardo',
    nome: 'Arpejo de Guerra',
    tipo: 'ataque',
    tags: [],
    nota: 'melodia',
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 5, impacto: 1 },
    cooldown: 3,
    texto: 'Se as 2 Ações anteriores tiveram Notas diferentes entre si, recebe +1 D e +1 I.',
  },
  {
    id: cardId('B10'),
    classe: 'bardo',
    nome: 'Afinar',
    tipo: 'tecnica',
    tags: [],
    nota: 'melodia',
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 1,
    texto:
      'Escolha a Nota de sua próxima Ação neste turno apenas para verificar Cadência. O texto e o tipo da próxima carta não mudam.',
  },
  {
    id: cardId('B11'),
    classe: 'bardo',
    nome: 'Improviso',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Escolha Pulso, Melodia ou Harmonia. Se a próxima Ação tiver Nota diferente, ela recebe +1 D ou +1 I se for Ataque.',
  },
  {
    id: cardId('B12'),
    classe: 'bardo',
    nome: 'Preparar o Refrão',
    tipo: 'tecnica',
    tags: [],
    nota: 'harmonia',
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'A próxima Ação neste turno com Nota diferente custa 1 AP a menos, mínimo 1.',
  },
  {
    id: cardId('B13'),
    classe: 'bardo',
    nome: 'Mudança de Tom',
    tipo: 'tecnica',
    tags: [],
    nota: 'melodia',
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Só pode ser usada se você já produziu Cadência neste turno. Mova uma habilidade sua de CD2 para CD1.',
  },
  {
    id: cardId('B14'),
    classe: 'bardo',
    nome: 'Pausa Dramática',
    tipo: 'tecnica',
    tags: [],
    nota: 'pulso',
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'No fim deste turno, ganhe +1 Reserva além da conversão normal, respeitando o máximo de 2.',
  },
  {
    id: cardId('B15'),
    classe: 'bardo',
    nome: 'Desafinar',
    tipo: 'tecnica',
    tags: [],
    nota: 'harmonia',
    custo: { moeda: 'ap', valor: 2 },
    cooldown: 3,
    texto:
      'Requer que você tenha produzido Cadência neste turno. A próxima carta de Reação adversária neste turno reduz 1 D e 1 I a menos. Se não houver Reação, sua terceira Ação, se for Ataque, recebe +1 D.',
  },
  {
    id: cardId('B16'),
    classe: 'bardo',
    nome: 'Contracanto',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto:
      'Reduza 2 D e 1 I. Se estiver respondendo à segunda ou terceira Ação inimiga, deixe Pronta uma Passiva sua Ativada, se houver.',
  },
  {
    id: cardId('B17'),
    classe: 'bardo',
    nome: 'Quebra de Ritmo',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto:
      'Reduza 3 I. Se impedir Ruptura, sua primeira Ação no próximo turno recebe +1 I se for Ataque.',
  },
  {
    id: cardId('B18'),
    classe: 'bardo',
    nome: 'Nota Sustentada',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto: 'Reduza 4 D.',
  },
  {
    id: cardId('B19'),
    classe: 'bardo',
    nome: 'Resposta Improvisada',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 2,
    texto:
      'Reduza 2 D. Se estiver respondendo à terceira Ação inimiga, sua primeira Ação do próximo turno custa 1 AP a menos, mínimo 1.',
  },
  {
    id: cardId('B20'),
    classe: 'bardo',
    nome: 'Coda Defensiva',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 3,
    texto: 'Reduza 3 D e 3 I. Depois, deixe Pronta 1 de suas Cartas de Classe Ativadas.',
  },
];
