import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Patrulheiro, transcritas de docs/CARD_CATALOG.md.
 *
 * A Marca da Presa é uma só e fica sobre o adversário. Ela não é custo: não
 * aparece dentro do custo impresso de carta nenhuma. Algumas cartas a usam sem
 * consumir; outras a Exploram, e aí ela é removida depois da resolução.
 */
export const HABILIDADES_DO_PATRULHEIRO: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('R01'),
    classe: 'patrulheiro',
    nome: 'Flecha de Sondagem',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto:
      'Se causar Dano à Vida e o adversário ainda não estiver Marcado, aplique a Marca da Presa.',
  },
  {
    id: cardId('R02'),
    classe: 'patrulheiro',
    nome: 'Tiro Preciso',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 4, impacto: 0 },
    cooldown: 2,
    texto: 'Se o alvo estiver Marcado, pode Explorar a Marca para receber +2 D.',
  },
  {
    id: cardId('R03'),
    classe: 'patrulheiro',
    nome: 'Flecha de Caça',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 2 },
    cooldown: 1,
    texto: 'Contra alvo Marcado, recebe +1 I sem consumir a Marca.',
  },
  {
    id: cardId('R04'),
    classe: 'patrulheiro',
    nome: 'Tiro Rompe-Guarda',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 2, impacto: 3 },
    cooldown: 2,
    texto: 'Pode Explorar a Marca antes da resolução para receber +2 I.',
  },
  {
    id: cardId('R05'),
    classe: 'patrulheiro',
    nome: 'Disparo Serrilhado',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto: 'Se atingir a Vida de um alvo Marcado, aplique Sangramento 1. A Marca não é consumida.',
  },
  {
    id: cardId('R06'),
    classe: 'patrulheiro',
    nome: 'Disparo em Movimento',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 0 },
    cooldown: 1,
    texto: 'Se for sua segunda ou terceira Ação e o alvo estiver Marcado, recebe +1 D.',
  },
  {
    id: cardId('R07'),
    classe: 'patrulheiro',
    nome: 'Flecha de Impacto',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 4, impacto: 3 },
    cooldown: 3,
    texto: 'Pode Explorar a Marca para receber +2 I.',
  },
  {
    id: cardId('R08'),
    classe: 'patrulheiro',
    nome: 'Tiro de Execução',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 6, impacto: 0 },
    cooldown: 3,
    texto: 'Só contra alvo Marcado com Guarda 0. Explora obrigatoriamente a Marca e recebe +2 D.',
  },
  {
    id: cardId('R09'),
    classe: 'patrulheiro',
    nome: 'Disparo de Cobertura',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto: 'Se o adversário usar uma carta de Reação, no fim do turno ganhe +1 Reserva, máximo 2.',
  },
  {
    id: cardId('R10'),
    classe: 'patrulheiro',
    nome: 'Flecha Rápida',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: 'Se a Ação imediatamente anterior foi Técnica, recebe +1 D.',
  },
  {
    id: cardId('R11'),
    classe: 'patrulheiro',
    nome: 'Marcar a Presa',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 1,
    texto:
      'Aplique a Marca da Presa. Se o alvo já estiver Marcado, seu próximo Ataque neste turno recebe +1 I.',
  },
  {
    id: cardId('R12'),
    classe: 'patrulheiro',
    nome: 'Ajustar a Mira',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 1,
    texto: 'Seu próximo Ataque contra alvo Marcado recebe +1 D e +1 I.',
  },
  {
    id: cardId('R13'),
    classe: 'patrulheiro',
    nome: 'Preparar Emboscada',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Escolha 1 Ataque da mão e coloque face-down no terceiro espaço de Ação. No próximo turno, ele está reservado para ser a terceira Ação e custa 1 AP a menos, mínimo 1. Se não for usado até o fim daquele turno, volta à mão.',
  },
  {
    id: cardId('R14'),
    classe: 'patrulheiro',
    nome: 'Reposicionar Armadilha',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 3,
    texto: 'Deixe Pronta sua Carta de Classe do tipo Armadilha se estiver Ativada.',
  },
  {
    id: cardId('R15'),
    classe: 'patrulheiro',
    nome: 'Paciência do Caçador',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Se o adversário estiver Marcado e você não Explorar a Marca neste turno, seu primeiro Ataque no próximo turno custa 1 AP a menos, mínimo 1.',
  },
  {
    id: cardId('R16'),
    classe: 'patrulheiro',
    nome: 'Esquiva Lateral',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 3 D.',
  },
  {
    id: cardId('R17'),
    classe: 'patrulheiro',
    nome: 'Aparar com o Arco',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 1 D e 2 I.',
  },
  {
    id: cardId('R18'),
    classe: 'patrulheiro',
    nome: 'Retirada Calculada',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto: 'Reduza 2 D e 2 I. Se o adversário ainda não estiver Marcado, aplique a Marca.',
  },
  {
    id: cardId('R19'),
    classe: 'patrulheiro',
    nome: 'Disparo de Reação',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto:
      'Reduza 2 D. Se o Dano final for 0, o adversário perde 2 Vida. Se ainda não estiver Marcado, aplique a Marca.',
  },
  {
    id: cardId('R20'),
    classe: 'patrulheiro',
    nome: 'Instinto de Caça',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 2,
    texto: 'Reduza 2 I. Se impedir Ruptura, aplique a Marca se ela ainda não existir.',
  },
];
