import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Bruxo, transcritas de docs/CARD_CATALOG.md.
 *
 * A moeda do Bruxo é a própria Vida. Perder Vida como custo não é Dano: não
 * pode ser reduzido e não conta como ter recebido um Ataque. Os custos que as
 * cartas oferecem são sempre opcionais e sempre separados do Preço Proibido.
 */
export const HABILIDADES_DO_BRUXO: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('BR01'),
    classe: 'bruxo',
    nome: 'Seta Sombria',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: 'Se já perdeu Vida por efeito próprio neste turno, recebe +1 D.',
  },
  {
    id: cardId('BR02'),
    classe: 'bruxo',
    nome: 'Chama Profana',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto:
      'Ao declarar, pode perder 1 Vida para receber +2 D. Esse preço é separado de Preço Proibido.',
  },
  {
    id: cardId('BR03'),
    classe: 'bruxo',
    nome: 'Correntes do Abismo',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 2, impacto: 3 },
    cooldown: 2,
    texto: 'Ao declarar, pode perder 1 Vida para receber +2 I.',
  },
  {
    id: cardId('BR04'),
    classe: 'bruxo',
    nome: 'Dreno Vital',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto:
      'Se causar Dano à Vida, restaure 1 Vida. Se perdeu Vida por efeito próprio neste turno, restaure 2 em vez disso.',
  },
  {
    id: cardId('BR05'),
    classe: 'bruxo',
    nome: 'Lança Profana',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 5, impacto: 2 },
    cooldown: 2,
    texto: 'Se Preço Proibido foi usado para jogar esta carta, recebe +1 D.',
  },
  {
    id: cardId('BR06'),
    classe: 'bruxo',
    nome: 'Fogo Infernal',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 5, impacto: 2 },
    cooldown: 3,
    texto:
      'Pode perder até 3 Vida adicionais ao declarar. Recebe +1 D por Vida perdida dessa forma.',
  },
  {
    id: cardId('BR07'),
    classe: 'bruxo',
    nome: 'Marca Dolorosa',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto: 'Se sua Maldição foi Ativada neste turno, recebe +2 D.',
  },
  {
    id: cardId('BR08'),
    classe: 'bruxo',
    nome: 'Ruptura do Pacto',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 3 },
    cooldown: 2,
    texto: 'Se seu Pacto estiver Ativado, recebe +1 I.',
  },
  {
    id: cardId('BR09'),
    classe: 'bruxo',
    nome: 'Cobrar o Preço',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 0 },
    cooldown: 1,
    texto: 'Se já perdeu pelo menos 2 Vida por efeitos próprios neste turno, recebe +2 D.',
  },
  {
    id: cardId('BR10'),
    classe: 'bruxo',
    nome: 'Boca do Abismo',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 4, impacto: 4 },
    cooldown: 3,
    texto: 'Se causar Ruptura, restaure 1 Vida ou deixe Pronta sua Maldição Ativada.',
  },
  {
    id: cardId('BR11'),
    classe: 'bruxo',
    nome: 'Assinar com Sangue',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'Perca 2 Vida. Seu próximo Ataque neste turno recebe +2 D e +1 I.',
  },
  {
    id: cardId('BR12'),
    classe: 'bruxo',
    nome: 'Invocar o Pacto',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'Deixe Pronto seu Pacto Ativado. Depois, perca 1 Vida.',
  },
  {
    id: cardId('BR13'),
    classe: 'bruxo',
    nome: 'Apertar a Maldição',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Deixe Pronta sua Maldição Ativada. Sua próxima habilidade ofensiva neste turno recebe +1 I.',
  },
  {
    id: cardId('BR14'),
    classe: 'bruxo',
    nome: 'Roubar Fôlego',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    cooldown: 2,
    texto:
      'Se perdeu Vida por efeito próprio neste turno, restaure 3 Vida. Caso contrário, restaure 1.',
  },
  {
    id: cardId('BR15'),
    classe: 'bruxo',
    nome: 'Pacto Apressado',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 3,
    texto:
      'Sua próxima habilidade de custo impresso 2 AP ou mais pode usar Preço Proibido mesmo se ele já foi usado neste turno.',
  },
  {
    id: cardId('BR16'),
    classe: 'bruxo',
    nome: 'Escudo Sombrio',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 3 D.',
  },
  {
    id: cardId('BR17'),
    classe: 'bruxo',
    nome: 'Correntes Defensivas',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 3 I.',
  },
  {
    id: cardId('BR18'),
    classe: 'bruxo',
    nome: 'Transferir a Dor',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 2,
    texto:
      'Reduza 3 D. Depois, você perde 1 Vida e o adversário perde 1 Vida. Essas perdas não podem ser reduzidas.',
  },
  {
    id: cardId('BR19'),
    classe: 'bruxo',
    nome: 'Pele do Abismo',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto: 'Reduza 2 D e 3 I. Pode perder 1 Vida para reduzir +2 D.',
  },
  {
    id: cardId('BR20'),
    classe: 'bruxo',
    nome: 'Sobreviver ao Preço',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 3,
    texto:
      'Só contra um Ataque que derrotaria você. Reduza 4 D. Se sobreviver com 3 ou menos de Vida, deixe Pronto seu Pacto.',
  },
];
