import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Mago, transcritas de docs/CARD_CATALOG.md.
 *
 * Todas são Feitiços. "Feitiço" é um traço impresso ao lado do tipo — Ataque,
 * Técnica ou Reação —, e não um quarto tipo universal: por isso ele aparece em
 * `tags` e nunca em `tipo`.
 */
export const HABILIDADES_DO_MAGO: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('M01'),
    classe: 'mago',
    nome: 'Dardo Arcano',
    tipo: 'ataque',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: 'Se pelo menos uma Runa estiver Ativada ao declarar, recebe +1 D.',
  },
  {
    id: cardId('M02'),
    classe: 'mago',
    nome: 'Bola de Fogo',
    tipo: 'ataque',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'mana', quantidade: 1 } },
    valores: { dano: 4, impacto: 1 },
    cooldown: 2,
    texto: 'Se o inimigo tiver Queimadura, recebe +1 D.',
  },
  {
    id: cardId('M03'),
    classe: 'mago',
    nome: 'Chama Persistente',
    tipo: 'ataque',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'mana', quantidade: 1 } },
    valores: { dano: 2, impacto: 1 },
    cooldown: 2,
    texto: 'Se causar Dano à Vida, aplique Queimadura 2.',
  },
  {
    id: cardId('M04'),
    classe: 'mago',
    nome: 'Pulso Cinético',
    tipo: 'ataque',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'mana', quantidade: 1 } },
    valores: { dano: 2, impacto: 3 },
    cooldown: 2,
    texto: 'Se causar Ruptura, recupere 1 Mana.',
  },
  {
    id: cardId('M05'),
    classe: 'mago',
    nome: 'Lança Arcana',
    tipo: 'ataque',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 3, recurso: { recurso: 'mana', quantidade: 2 } },
    valores: { dano: 5, impacto: 2 },
    cooldown: 2,
    texto: 'Se for sua terceira Ação do turno, recebe +1 D.',
  },
  {
    id: cardId('M06'),
    classe: 'mago',
    nome: 'Estilhaço de Gelo',
    tipo: 'ataque',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'mana', quantidade: 1 } },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto: 'Se causar Dano à Vida, aplique Lento 1.',
  },
  {
    id: cardId('M07'),
    classe: 'mago',
    nome: 'Onda Glacial',
    tipo: 'ataque',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 3, recurso: { recurso: 'mana', quantidade: 2 } },
    valores: { dano: 3, impacto: 3 },
    cooldown: 3,
    texto: 'Se causar Ruptura, aplique Lento 1.',
  },
  {
    id: cardId('M08'),
    classe: 'mago',
    nome: 'Rajada Prismática',
    tipo: 'ataque',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'mana', quantidade: 1 } },
    valores: { dano: 3, impacto: 1 },
    cooldown: 1,
    texto: 'Você pode Ativar uma Runa Pronta ao declarar. Se fizer isso, escolha +1 D ou +1 I.',
  },
  {
    id: cardId('M09'),
    classe: 'mago',
    nome: 'Orbe Instável',
    tipo: 'ataque',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 1, recurso: { recurso: 'mana', quantidade: 1 } },
    valores: { dano: 1, impacto: 2 },
    cooldown: 2,
    texto: 'Se for sua segunda Ação, escolha +1 D ou +1 I.',
  },
  {
    id: cardId('M10'),
    classe: 'mago',
    nome: 'Explosão de Mana',
    tipo: 'ataque',
    tags: ['feitico'],
    custo: {
      moeda: 'ap',
      valor: 2,
      recurso: { recurso: 'mana', quantidade: 1 },
      variavel: { recurso: 'mana', minimo: 0, maximo: 2 },
    },
    valores: { dano: 2, impacto: 1 },
    cooldown: 2,
    texto: 'Recebe +1 D por Mana adicional gasta nesta carta.',
  },
  {
    id: cardId('M11'),
    classe: 'mago',
    nome: 'Canalizar',
    tipo: 'tecnica',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 1,
    texto: 'Ganhe 2 Mana, até o máximo.',
  },
  {
    id: cardId('M12'),
    classe: 'mago',
    nome: 'Concentração Prismática',
    tipo: 'tecnica',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'Seu próximo Ataque/Feitiço neste turno recebe +1 D e +1 I.',
  },
  {
    id: cardId('M13'),
    classe: 'mago',
    nome: 'Distorção Temporal',
    tipo: 'tecnica',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'mana', quantidade: 2 } },
    cooldown: 3,
    texto: 'Escolha uma carta sua em CD1 e devolva-a imediatamente à mão.',
  },
  {
    id: cardId('M14'),
    classe: 'mago',
    nome: 'Recalibrar Runa',
    tipo: 'tecnica',
    tags: ['feitico'],
    custo: { moeda: 'ap', valor: 1, recurso: { recurso: 'mana', quantidade: 1 } },
    cooldown: 2,
    texto: 'Deixe Pronta uma de suas Runas Ativadas.',
  },
  {
    id: cardId('M15'),
    classe: 'mago',
    nome: 'Barreira de Mana',
    tipo: 'reacao',
    tags: ['feitico'],
    custo: { moeda: 'reserva', valor: 1, recurso: { recurso: 'mana', quantidade: 1 } },
    cooldown: 1,
    texto: 'Reduza 3 D.',
  },
  {
    id: cardId('M16'),
    classe: 'mago',
    nome: 'Imagem Espelhada',
    tipo: 'reacao',
    tags: ['feitico'],
    custo: { moeda: 'reserva', valor: 2, recurso: { recurso: 'mana', quantidade: 1 } },
    cooldown: 2,
    texto: 'O Dano final deste Ataque se torna 0. O Impacto não é alterado.',
  },
  {
    id: cardId('M17'),
    classe: 'mago',
    nome: 'Égide Cinética',
    tipo: 'reacao',
    tags: ['feitico'],
    custo: { moeda: 'reserva', valor: 1, recurso: { recurso: 'mana', quantidade: 1 } },
    cooldown: 1,
    texto: 'Reduza 3 I.',
  },
  {
    id: cardId('M18'),
    classe: 'mago',
    nome: 'Armadura de Gelo',
    tipo: 'reacao',
    tags: ['feitico'],
    custo: { moeda: 'reserva', valor: 1, recurso: { recurso: 'mana', quantidade: 1 } },
    cooldown: 2,
    texto: 'Reduza 2 D e 1 I. Se o Dano final for 0, aplique Lento 1 ao atacante.',
  },
  {
    id: cardId('M19'),
    classe: 'mago',
    nome: 'Contrafeitiço',
    tipo: 'reacao',
    tags: ['feitico'],
    custo: { moeda: 'reserva', valor: 2, recurso: { recurso: 'mana', quantidade: 2 } },
    cooldown: 3,
    texto:
      'Quando o adversário jogar uma Técnica, cancele o texto dela. Custos e espaço de Ação continuam gastos.',
  },
  {
    id: cardId('M20'),
    classe: 'mago',
    nome: 'Barreira Prismática',
    tipo: 'reacao',
    tags: ['feitico'],
    custo: { moeda: 'reserva', valor: 2, recurso: { recurso: 'mana', quantidade: 2 } },
    cooldown: 2,
    texto: 'Reduza 2 D e 2 I. Depois, deixe Pronta uma Runa Ativada.',
  },
];
