import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Bárbaro, transcritas de docs/CARD_CATALOG.md.
 *
 * A Guarda é o combustível, mas ela não entra no custo impresso: o texto diz
 * "**pode** reduzir voluntariamente", e reduzir é escolha de quem joga.
 * Habilidades normais não passam de 2 pontos por próprio turno; Ultimates e
 * efeitos de Exaurir podem ultrapassar esse teto.
 */
export const HABILIDADES_DO_BARBARO: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('BA01'),
    classe: 'barbaro',
    nome: 'Machado Curto',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: 'Se estiver Enfurecido, recebe +1 D.',
  },
  {
    id: cardId('BA02'),
    classe: 'barbaro',
    nome: 'Ombro Selvagem',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 2 },
    cooldown: 1,
    texto: 'Pode reduzir voluntariamente a própria Guarda em 1 para receber +1 I.',
  },
  {
    id: cardId('BA03'),
    classe: 'barbaro',
    nome: 'Golpe Temerário',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 4, impacto: 1 },
    cooldown: 2,
    texto: 'Pode reduzir voluntariamente a própria Guarda em 2 para receber +2 D.',
  },
  {
    id: cardId('BA04'),
    classe: 'barbaro',
    nome: 'Investida Bestial',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 3 },
    cooldown: 2,
    texto: 'Se estiver Enfurecido ou Desencadeado, recebe +1 I.',
  },
  {
    id: cardId('BA05'),
    classe: 'barbaro',
    nome: 'Quebra-Crânio',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 5, impacto: 2 },
    cooldown: 2,
    texto: 'Se estiver Desencadeado, recebe +2 D.',
  },
  {
    id: cardId('BA06'),
    classe: 'barbaro',
    nome: 'Corte em Frenesi',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 0 },
    cooldown: 1,
    texto: 'Se a Ação anterior foi Ataque e você estiver Enfurecido ou Desencadeado, recebe +2 D.',
  },
  {
    id: cardId('BA07'),
    classe: 'barbaro',
    nome: 'Machado Arremessado',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 4, impacto: 0 },
    cooldown: 2,
    texto: 'Não depende de sacrificar Guarda.',
  },
  {
    id: cardId('BA08'),
    classe: 'barbaro',
    nome: 'Golpe de Sangue',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto: 'Se estiver com 15 de Vida ou menos, recebe +2 D.',
  },
  {
    id: cardId('BA09'),
    classe: 'barbaro',
    nome: 'Martelo da Fera',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 4, impacto: 4 },
    cooldown: 3,
    texto: 'Pode reduzir voluntariamente a própria Guarda em 2 para receber +1 D e +1 I.',
  },
  {
    id: cardId('BA10'),
    classe: 'barbaro',
    nome: 'Fúria Final',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 6, impacto: 1 },
    cooldown: 3,
    texto:
      'Só pode ser usada enquanto estiver Desencadeado. Recebe +1 D por Ataque anterior neste turno, máximo +2 D.',
  },
  {
    id: cardId('BA11'),
    classe: 'barbaro',
    nome: 'Rugido de Guerra',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 1,
    texto:
      'Seu próximo Ataque recebe +1 D e +1 I. Se estiver Enfurecido ou Desencadeado, recebe +1 D adicional.',
  },
  {
    id: cardId('BA12'),
    classe: 'barbaro',
    nome: 'Quebrar Limites',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Reduza voluntariamente sua Guarda em 2. Seu próximo Ataque custa 1 AP a menos, mínimo 1.',
  },
  {
    id: cardId('BA13'),
    classe: 'barbaro',
    nome: 'Frenesi',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Os próximos 2 Ataques deste turno recebem +1 D. Depois que cada um resolver, reduza voluntariamente sua Guarda em 1, respeitando o limite normal de 2 por turno.',
  },
  {
    id: cardId('BA14'),
    classe: 'barbaro',
    nome: 'Desafiar a Dor',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Só com 15 de Vida ou menos. Seu próximo Ataque recebe +2 D. Você não pode restaurar Guarda por efeitos próprios neste turno.',
  },
  {
    id: cardId('BA15'),
    classe: 'barbaro',
    nome: 'Grito Ameaçador',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'A próxima carta de Reação contra um Ataque seu reduz 1 D e 1 I a menos.',
  },
  {
    id: cardId('BA16'),
    classe: 'barbaro',
    nome: 'Pele Grossa',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 3 D.',
  },
  {
    id: cardId('BA17'),
    classe: 'barbaro',
    nome: 'Aparar com o Machado',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 3 I. Se impedir Ruptura, seu primeiro Ataque no próximo turno recebe +1 I.',
  },
  {
    id: cardId('BA18'),
    classe: 'barbaro',
    nome: 'Aceitar o Golpe',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 2,
    texto:
      'Reduza 1 D. Depois da resolução, reduza voluntariamente a própria Guarda em até 2. Para cada ponto perdido, seu primeiro Ataque no próximo turno recebe +1 D.',
  },
  {
    id: cardId('BA19'),
    classe: 'barbaro',
    nome: 'Rugido de Retaliação',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto:
      'Reduza 2 D e 2 I. Se ainda perder Vida, seu primeiro Ataque no próximo turno recebe +1 D.',
  },
  {
    id: cardId('BA20'),
    classe: 'barbaro',
    nome: 'Último Fôlego',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 3,
    texto:
      'Só contra um Ataque que reduziria sua Vida a 0. Reduza 4 D. Depois da resolução, ajuste sua Guarda para 0.',
  },
];
