import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Necromante, transcritas de docs/CARD_CATALOG.md.
 *
 * A Alma é moeda: ela aparece dentro do custo impresso, ao lado dos pontos de
 * Ação ou da Reserva. Gastar uma Alma manda a ficha para o Cemitério — as
 * quatro fichas nunca deixam de existir, só mudam de pilha.
 */
export const HABILIDADES_DO_NECROMANTE: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('N01'),
    classe: 'necromante',
    nome: 'Flecha Óssea',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: '—',
  },
  {
    id: cardId('N02'),
    classe: 'necromante',
    nome: 'Lança de Ossos',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'alma', quantidade: 1 } },
    valores: { dano: 3, impacto: 3 },
    cooldown: 2,
    texto: 'A Alma gasta volta ao Cemitério.',
  },
  {
    id: cardId('N03'),
    classe: 'necromante',
    nome: 'Toque Murchante',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'alma', quantidade: 1 } },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto: 'Se causar Dano à Vida, aplique Murchar 1.',
  },
  {
    id: cardId('N04'),
    classe: 'necromante',
    nome: 'Drenar Vitalidade',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'alma', quantidade: 1 } },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto: 'Se causar Dano à Vida, restaure 1 Vida.',
  },
  {
    id: cardId('N05'),
    classe: 'necromante',
    nome: 'Onda dos Mortos',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3, recurso: { recurso: 'alma', quantidade: 2 } },
    valores: { dano: 4, impacto: 3 },
    cooldown: 3,
    texto: 'Se seus 2 Servos estiverem Prontos ao declarar, recebe +1 I.',
  },
  {
    id: cardId('N06'),
    classe: 'necromante',
    nome: 'Ceifa Funesta',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'alma', quantidade: 1 } },
    valores: { dano: 4, impacto: 1 },
    cooldown: 2,
    texto: 'Ao declarar, você pode remover 1 Murchar do adversário. Se fizer isso, recebe +2 D.',
  },
  {
    id: cardId('N07'),
    classe: 'necromante',
    nome: 'Mão do Túmulo',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 2, impacto: 2 },
    cooldown: 1,
    texto: 'Se o adversário estiver com 3 ou menos de Guarda, colha 1 Alma depois da resolução.',
  },
  {
    id: cardId('N08'),
    classe: 'necromante',
    nome: 'Roubo de Memória',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'alma', quantidade: 2 } },
    valores: { dano: 2, impacto: 1 },
    cooldown: 3,
    texto: 'Se causar Dano à Vida, escolha uma habilidade adversária em CD1 e mova para CD2.',
  },
  {
    id: cardId('N09'),
    classe: 'necromante',
    nome: 'Ruína Sepulcral',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1, recurso: { recurso: 'alma', quantidade: 1 } },
    valores: { dano: 1, impacto: 2 },
    cooldown: 1,
    texto: 'Se causar Ruptura, colha até 2 Almas do Cemitério.',
  },
  {
    id: cardId('N10'),
    classe: 'necromante',
    nome: 'Colheita Profana',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'Escolha uma habilidade sua em CD1 e mova para CD2. Colha até 2 Almas do Cemitério.',
  },
  {
    id: cardId('N11'),
    classe: 'necromante',
    nome: 'Oferenda ao Túmulo',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Escolha outra habilidade em sua mão e coloque-a em CD2. Colha até 3 Almas do Cemitério.',
  },
  {
    id: cardId('N12'),
    classe: 'necromante',
    nome: 'Desenterrar',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'alma', quantidade: 2 } },
    cooldown: 2,
    texto: 'Escolha uma carta sua em CD2 ou CD3 e mova uma etapa em direção à mão.',
  },
  {
    id: cardId('N13'),
    classe: 'necromante',
    nome: 'Comandar os Mortos',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1, recurso: { recurso: 'alma', quantidade: 1 } },
    cooldown: 2,
    texto: 'Deixe Pronto um Servo Ativado.',
  },
  {
    id: cardId('N14'),
    classe: 'necromante',
    nome: 'Selo Fúnebre',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1, recurso: { recurso: 'alma', quantidade: 1 } },
    cooldown: 2,
    texto: 'Aplique Murchar 1 ao adversário.',
  },
  {
    id: cardId('N15'),
    classe: 'necromante',
    nome: 'Rito de Ossos',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1, recurso: { recurso: 'alma', quantidade: 1 } },
    cooldown: 2,
    texto:
      'Seu próximo Ataque neste turno recebe +2 I. Se provocar Ruptura, deixe Pronto um Servo Ativado.',
  },
  {
    id: cardId('N16'),
    classe: 'necromante',
    nome: 'Muralha de Ossos',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1, recurso: { recurso: 'alma', quantidade: 1 } },
    cooldown: 1,
    texto: 'Reduza 3 I.',
  },
  {
    id: cardId('N17'),
    classe: 'necromante',
    nome: 'Véu dos Mortos',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1, recurso: { recurso: 'alma', quantidade: 1 } },
    cooldown: 1,
    texto: 'Reduza 3 D.',
  },
  {
    id: cardId('N18'),
    classe: 'necromante',
    nome: 'Retorno Sepulcral',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2, recurso: { recurso: 'alma', quantidade: 2 } },
    cooldown: 2,
    texto: 'Reduza 2 D e 2 I. Depois da resolução, devolva uma carta sua de CD1 à mão.',
  },
  {
    id: cardId('N19'),
    classe: 'necromante',
    nome: 'Recusar a Morte',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2, recurso: { recurso: 'alma', quantidade: 3 } },
    cooldown: 3,
    texto:
      'Só contra um Ataque que reduziria sua Vida a 0. A ação resolve e depois sua Vida fica em 1.',
  },
  {
    id: cardId('N20'),
    classe: 'necromante',
    nome: 'Maldição Reflexa',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1, recurso: { recurso: 'alma', quantidade: 1 } },
    cooldown: 2,
    texto: 'Reduza 1 D e 1 I. Se ainda perder Vida, aplique Murchar 1 ao adversário.',
  },
];
