import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Clérigo, transcritas de docs/CARD_CATALOG.md.
 *
 * "Requer Graça ou mais" é condição de uso, não custo: a Devoção não é gasta
 * para pagar a carta, ela é um estado que precisa estar de pé na hora de
 * declarar. Por isso nada disso aparece em `custo` — quem confere é a
 * legalidade da carta.
 */
export const HABILIDADES_DO_CLERIGO: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('C01'),
    classe: 'clerigo',
    nome: 'Golpe Consagrado',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: 'Se o adversário estiver com 3 ou menos de Guarda, recebe +1 I.',
  },
  {
    id: cardId('C02'),
    classe: 'clerigo',
    nome: 'Martelo do Julgamento',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 2 },
    cooldown: 1,
    texto:
      'Se o adversário usar uma carta de Reação e este Ataque ainda causar Dano à Vida, avance 1 estágio de Devoção depois da resolução. Esse avanço é adicional ao avanço normal do turno.',
  },
  {
    id: cardId('C03'),
    classe: 'clerigo',
    nome: 'Luz Punitiva',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 4, impacto: 1 },
    cooldown: 2,
    texto:
      'Requer Graça ou mais. Se o inimigo já estava com Guarda 0 e o Ataque causar Dano à Vida, restaure 1 Vida.',
  },
  {
    id: cardId('C04'),
    classe: 'clerigo',
    nome: 'Veredito Solar',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 2, impacto: 3 },
    cooldown: 2,
    texto: 'Requer Graça ou mais. Se causar Ruptura, restaure 1 Vida depois da resolução.',
  },
  {
    id: cardId('C05'),
    classe: 'clerigo',
    nome: 'Lança da Aurora',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 3, impacto: 0 },
    cooldown: 1,
    texto: 'Requer Graça ou mais. Se você restaurou Vida neste turno, recebe +2 D.',
  },
  {
    id: cardId('C06'),
    classe: 'clerigo',
    nome: 'Julgamento Maior',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 5, impacto: 2 },
    cooldown: 2,
    texto:
      'Requer Fervor ou Milagre. Se for sua terceira Ação e o inimigo estiver com Guarda 0, recebe +2 D. Depois da resolução, desça 1 estágio de Devoção.',
  },
  {
    id: cardId('C07'),
    classe: 'clerigo',
    nome: 'Cinzas do Pecado',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 2 },
    cooldown: 2,
    texto: 'Requer Graça ou mais. Se causar Dano à Vida, remova 1 Condição negativa sua.',
  },
  {
    id: cardId('C08'),
    classe: 'clerigo',
    nome: 'Oração Silenciosa',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'Avance 1 estágio de Devoção.',
  },
  {
    id: cardId('C09'),
    classe: 'clerigo',
    nome: 'Prece Restauradora',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    cooldown: 2,
    texto: 'Requer Graça ou mais. Restaure 3 Vida.',
  },
  {
    id: cardId('C10'),
    classe: 'clerigo',
    nome: 'Imposição das Mãos',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    cooldown: 3,
    texto:
      'Só pode ser usada com 15 de Vida ou menos e requer Fervor ou Milagre. Restaure 5 Vida. Depois da resolução, desça 1 estágio de Devoção.',
  },
  {
    id: cardId('C11'),
    classe: 'clerigo',
    nome: 'Bênção da Coragem',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 1,
    texto: 'Requer Graça ou mais. Seu próximo Ataque neste turno recebe +1 D e +1 I.',
  },
  {
    id: cardId('C12'),
    classe: 'clerigo',
    nome: 'Vigília',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'No fim deste turno, ganhe +1 Reserva além da conversão normal, respeitando o máximo de 2. Se terminar com 2 de Reserva, avance 1 estágio de Devoção.',
  },
  {
    id: cardId('C13'),
    classe: 'clerigo',
    nome: 'Purificação',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Requer Graça ou mais. Remova 1 Condição negativa. Se não houver nenhuma, restaure 2 Vida.',
  },
  {
    id: cardId('C14'),
    classe: 'clerigo',
    nome: 'Escudo da Fé',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Requer Graça ou mais. Reduza 2 D e 2 I.',
  },
  {
    id: cardId('C15'),
    classe: 'clerigo',
    nome: 'Âncora Sagrada',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Requer Graça ou mais. Reduza 3 I.',
  },
  {
    id: cardId('C16'),
    classe: 'clerigo',
    nome: 'Intercessão',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto: 'Requer Fervor ou Milagre. Reduza 4 D. Depois da resolução, desça 1 estágio de Devoção.',
  },
  {
    id: cardId('C17'),
    classe: 'clerigo',
    nome: 'Martírio',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 2,
    texto:
      'Reduza 3 I. Se impedir uma Ruptura, perca 1 Vida que não pode ser reduzida e avance 1 estágio de Devoção.',
  },
  {
    id: cardId('C18'),
    classe: 'clerigo',
    nome: 'Luz Refletida',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto:
      'Requer Fervor ou Milagre. Reduza 2 D e 2 I. Se o Dano final for 0, o adversário perde 2 de Vida. Depois da resolução, desça 1 estágio de Devoção.',
  },
  {
    id: cardId('C19'),
    classe: 'clerigo',
    nome: 'Absolvição',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 2,
    texto:
      'Requer Graça ou mais. Reduza 1 D e 1 I. Condições que esta ação aplicaria a você não são aplicadas.',
  },
  {
    id: cardId('C20'),
    classe: 'clerigo',
    nome: 'Última Prece',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 3,
    texto:
      'Só pode ser usada com 10 de Vida ou menos e requer Fervor ou Milagre. Reduza 5 D e depois restaure 1 Vida. Depois da resolução, desça 1 estágio de Devoção.',
  },
];
