import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Paladino, transcritas de docs/CARD_CATALOG.md.
 *
 * A Convicção não é moeda: "Requer Resoluto ou Inabalável" é condição de uso, e
 * "desça 1 estado" é preço cobrado em estado, não em recurso. Nada disso entra
 * no custo impresso.
 */
export const HABILIDADES_DO_PALADINO: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('P01'),
    classe: 'paladino',
    nome: 'Pancada de Escudo',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 1, impacto: 2 },
    cooldown: 1,
    texto: 'Se sua Guarda estiver em 6 ao declarar, recebe +1 I.',
  },
  {
    id: cardId('P02'),
    classe: 'paladino',
    nome: 'Corte Radiante',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 1,
    texto:
      'Se estiver Resoluto ou Inabalável, você pode descer 1 estado ao declarar para receber +2 D.',
  },
  {
    id: cardId('P03'),
    classe: 'paladino',
    nome: 'Martelo do Juramento',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 2, impacto: 3 },
    cooldown: 2,
    texto: 'Se começou este turno com 2 de Reserva, recebe +1 D.',
  },
  {
    id: cardId('P04'),
    classe: 'paladino',
    nome: 'Golpe Consagrado',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 4, impacto: 2 },
    cooldown: 2,
    texto:
      'Requer Resoluto ou Inabalável. Se causar Ruptura, cumpra o requisito de avanço do seu Juramento uma vez, se ainda não o cumpriu neste ciclo.',
  },
  {
    id: cardId('P05'),
    classe: 'paladino',
    nome: 'Reprimenda',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 2,
    texto:
      'Se o adversário usou uma carta de Reação contra uma ação anterior neste turno, recebe +2 D.',
  },
  {
    id: cardId('P06'),
    classe: 'paladino',
    nome: 'Investida do Bastião',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 4, impacto: 3 },
    cooldown: 2,
    texto: 'Se sua Guarda estiver em 4 ou mais, recebe +1 D.',
  },
  {
    id: cardId('P07'),
    classe: 'paladino',
    nome: 'Sentença Sagrada',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 5, impacto: 2 },
    cooldown: 3,
    texto:
      'Requer Inabalável. Ao declarar, você pode descer para Resoluto. Se fizer isso e o adversário estiver com Guarda 0, recebe +2 D.',
  },
  {
    id: cardId('P08'),
    classe: 'paladino',
    nome: 'Golpe de Retaliação',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto: 'Se você usou uma carta de Reação desde o fim do seu último turno, recebe +1 D e +1 I.',
  },
  {
    id: cardId('P09'),
    classe: 'paladino',
    nome: 'Romper a Linha',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 2, impacto: 4 },
    cooldown: 3,
    texto:
      'Requer Resoluto ou Inabalável. Se estiver Inabalável, você pode descer para Resoluto para receber +1 D.',
  },
  {
    id: cardId('P10'),
    classe: 'paladino',
    nome: 'Lâmina da Aurora',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 3, impacto: 0 },
    cooldown: 1,
    texto: 'Se for sua terceira Ação do turno e você estiver Resoluto ou Inabalável, recebe +2 D.',
  },
  {
    id: cardId('P11'),
    classe: 'paladino',
    nome: 'Preparar o Bastião',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 1,
    texto:
      'No fim deste turno, ganhe +1 Reserva além da conversão normal, respeitando o máximo de 2.',
  },
  {
    id: cardId('P12'),
    classe: 'paladino',
    nome: 'Consagrar Arma',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'Requer Resoluto ou Inabalável. Seu próximo Ataque neste turno recebe +1 D e +2 I.',
  },
  {
    id: cardId('P13'),
    classe: 'paladino',
    nome: 'Renovar o Juramento',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Suba 1 estado de Convicção, máximo Inabalável. Você não pode realizar outra Técnica neste turno.',
  },
  {
    id: cardId('P14'),
    classe: 'paladino',
    nome: 'Marcha Implacável',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'Seu próximo Ataque de custo impresso 2 AP ou mais custa 1 AP a menos, mínimo 1.',
  },
  {
    id: cardId('P15'),
    classe: 'paladino',
    nome: 'Bloqueio de Torre',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto:
      'Reduza 3 I. Se impedir Ruptura, aplique normalmente a condição de avanço do Juramento da Proteção caso seja o seu Juramento.',
  },
  {
    id: cardId('P16'),
    classe: 'paladino',
    nome: 'Égide Sagrada',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Requer Resoluto ou Inabalável. Reduza 2 D e 2 I.',
  },
  {
    id: cardId('P17'),
    classe: 'paladino',
    nome: 'Repreensão Divina',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto:
      'Requer Resoluto ou Inabalável. Reduza 3 D. Se o Dano final for 0, o adversário perde 2 de Vida.',
  },
  {
    id: cardId('P18'),
    classe: 'paladino',
    nome: 'Permanecer de Pé',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto: 'Só contra um Ataque que causaria Ruptura. Reduza 4 I.',
  },
  {
    id: cardId('P19'),
    classe: 'paladino',
    nome: 'Escudo e Espada',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 2,
    texto:
      'Requer Resoluto ou Inabalável. Reduza 2 D e 1 I. Se ainda perder Vida, seu primeiro Ataque no próximo turno recebe +1 D.',
  },
  {
    id: cardId('P20'),
    classe: 'paladino',
    nome: 'Não Passará',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 3,
    texto: 'Requer Inabalável. Reduza 3 D e 3 I. Depois da resolução, desça para Resoluto.',
  },
];
