import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Guerreiro, transcritas de docs/CARD_CATALOG.md.
 *
 * Os identificadores W01 a W20 são os do próprio documento e não mudam. Nenhum
 * número aqui é ajuste de balanceamento: o que está no documento é o que está
 * aqui.
 */
export const HABILIDADES_DO_GUERREIRO: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('W01'),
    classe: 'guerreiro',
    nome: 'Corte de Sondagem',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto:
      'Se o adversário usar uma carta de Reação contra este Ataque, ganhe 1 Momentum depois da resolução.',
  },
  {
    id: cardId('W02'),
    classe: 'guerreiro',
    nome: 'Ombro de Guerra',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 2 },
    cooldown: 1,
    texto: 'Se for sua primeira Ação do turno, recebe +1 I.',
  },
  {
    id: cardId('W03'),
    classe: 'guerreiro',
    nome: 'Quebra-Escudo',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 2, impacto: 3 },
    cooldown: 2,
    texto: 'Se causar Ruptura, ganhe 1 Momentum.',
  },
  {
    id: cardId('W04'),
    classe: 'guerreiro',
    nome: 'Corte Ascendente',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 4, impacto: 1 },
    cooldown: 2,
    texto: 'Se o inimigo já estava com Guarda 0 quando esta carta foi declarada, recebe +2 D.',
  },
  {
    id: cardId('W05'),
    classe: 'guerreiro',
    nome: 'Golpe do Carrasco',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3, variavel: { recurso: 'momentum', minimo: 0, maximo: 2 } },
    valores: { dano: 5, impacto: 1 },
    cooldown: 2,
    texto: 'Ao declarar, gaste até 2 Momentum. Recebe +1 D por Momentum gasto.',
  },
  {
    id: cardId('W06'),
    classe: 'guerreiro',
    nome: 'Sequência Brutal',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto: 'Se for sua terceira Ação do turno, recebe +2 D.',
  },
  {
    id: cardId('W07'),
    classe: 'guerreiro',
    nome: 'Finta Cortante',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 1, impacto: 1 },
    cooldown: 1,
    texto: 'Se o adversário usar uma carta de Reação, recupere 1 AP depois da resolução.',
  },
  {
    id: cardId('W08'),
    classe: 'guerreiro',
    nome: 'Golpe de Cerco',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 3, impacto: 4 },
    cooldown: 3,
    texto: 'Se causar Ruptura, o bônus de Ruptura deste Ataque é +3 D em vez de +2 D.',
  },
  {
    id: cardId('W09'),
    classe: 'guerreiro',
    nome: 'Corte Encadeado',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 1,
    texto: 'Se sua Ação anterior foi um Ataque de 1 AP, recebe +1 D e +1 I.',
  },
  {
    id: cardId('W10'),
    classe: 'guerreiro',
    nome: 'Ataque de Oportunidade',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 3, impacto: 0 },
    cooldown: 2,
    texto: 'Só pode ser usado se o inimigo estiver com Guarda 0.',
  },
  {
    id: cardId('W11'),
    classe: 'guerreiro',
    nome: 'Pressão Implacável',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'Seu próximo Ataque neste turno recebe +2 I. Se ele causar Ruptura, ganhe 1 Momentum.',
  },
  {
    id: cardId('W12'),
    classe: 'guerreiro',
    nome: 'Disciplina de Aço',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 1,
    texto: 'Ganhe 1 Momentum. Se terminar o turno com 2 de Reserva, ganhe mais 1 Momentum.',
  },
  {
    id: cardId('W13'),
    classe: 'guerreiro',
    nome: 'Finta Calculada',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Seu próximo Ataque neste turno recebe +2 D se enfrentar uma carta de Reação. Se não enfrentar, recebe +2 I.',
  },
  {
    id: cardId('W14'),
    classe: 'guerreiro',
    nome: 'Guarda Preparada',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'No fim deste turno, ganhe +1 Reserva além da conversão normal, respeitando o máximo de 2.',
  },
  {
    id: cardId('W15'),
    classe: 'guerreiro',
    nome: 'Aparar',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 3 D. Se o Dano final for 0, ganhe 1 Momentum.',
  },
  {
    id: cardId('W16'),
    classe: 'guerreiro',
    nome: 'Base Firme',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 3 I. Se isso impedir uma Ruptura, ganhe 1 Momentum.',
  },
  {
    id: cardId('W17'),
    classe: 'guerreiro',
    nome: 'Absorver o Golpe',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto: 'Reduza 2 D e 2 I. Se ainda perder Vida, ganhe 1 Momentum.',
  },
  {
    id: cardId('W18'),
    classe: 'guerreiro',
    nome: 'Ripostar',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto: 'Reduza 2 D. Se o Dano final for 0, o adversário perde 2 de Vida.',
  },
  {
    id: cardId('W19'),
    classe: 'guerreiro',
    nome: 'Interposição',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 2,
    texto: 'Reduza 1 D e 2 I.',
  },
  {
    id: cardId('W20'),
    classe: 'guerreiro',
    nome: 'Último Bastião',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 3,
    texto: 'Só contra um Ataque que causaria Ruptura. Reduza 1 D e 3 I.',
  },
];
