import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Monge, transcritas de docs/CARD_CATALOG.md.
 *
 * A etapa de Kata — Abertura, Fluxo, Finalização — é dado impresso, como a
 * Nota do Bardo. As Reações não têm etapa: o Kata é uma sequência de Ações do
 * próprio turno.
 *
 * O Chi é moeda e aparece dentro do custo. Gastar vira a pedra para o lado
 * Gasto; recuperar a vira de volta. As três pedras nunca deixam de existir.
 */
export const HABILIDADES_DO_MONGE: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('MO01'),
    classe: 'monge',
    nome: 'Palma de Ferro',
    tipo: 'ataque',
    tags: [],
    kata: 'abertura',
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: 'Se for sua primeira Ação, recebe +1 I.',
  },
  {
    id: cardId('MO02'),
    classe: 'monge',
    nome: 'Chute do Calcanhar',
    tipo: 'ataque',
    tags: [],
    kata: 'abertura',
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 2 },
    cooldown: 1,
    texto: 'Se o adversário estiver com Guarda 6, recebe +1 I.',
  },
  {
    id: cardId('MO03'),
    classe: 'monge',
    nome: 'Toque dos Nervos',
    tipo: 'ataque',
    tags: [],
    kata: 'abertura',
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'chi', quantidade: 1 } },
    valores: { dano: 2, impacto: 2 },
    cooldown: 2,
    texto: 'Sua próxima Ação de Fluxo neste turno recebe +1 D.',
  },
  {
    id: cardId('MO04'),
    classe: 'monge',
    nome: 'Passo do Vento',
    tipo: 'ataque',
    tags: [],
    kata: 'fluxo',
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: 'Se vier imediatamente depois de Abertura, recebe +1 D.',
  },
  {
    id: cardId('MO05'),
    classe: 'monge',
    nome: 'Joelhada Ascendente',
    tipo: 'ataque',
    tags: [],
    kata: 'fluxo',
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 2 },
    cooldown: 2,
    texto: 'Se vier imediatamente depois de Abertura, recebe +1 I.',
  },
  {
    id: cardId('MO06'),
    classe: 'monge',
    nome: 'Cotovelo Giratório',
    tipo: 'ataque',
    tags: [],
    kata: 'fluxo',
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'chi', quantidade: 1 } },
    valores: { dano: 4, impacto: 1 },
    cooldown: 2,
    texto: 'Se o adversário usar uma carta de Reação, recupere 1 Chi Gasto depois da resolução.',
  },
  {
    id: cardId('MO07'),
    classe: 'monge',
    nome: 'Punho do Dragão',
    tipo: 'ataque',
    tags: [],
    kata: 'finalizacao',
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'chi', quantidade: 1 } },
    valores: { dano: 4, impacto: 2 },
    cooldown: 2,
    texto: 'Se vier imediatamente depois de Fluxo, recebe +1 D.',
  },
  {
    id: cardId('MO08'),
    classe: 'monge',
    nome: 'Martelo Descendente',
    tipo: 'ataque',
    tags: [],
    kata: 'finalizacao',
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 5, impacto: 2 },
    cooldown: 2,
    texto: 'Se provocar Ruptura depois de Fluxo, recupere 1 Chi Gasto.',
  },
  {
    id: cardId('MO09'),
    classe: 'monge',
    nome: 'Punho do Vazio',
    tipo: 'ataque',
    tags: [],
    kata: 'finalizacao',
    custo: { moeda: 'ap', valor: 2, recurso: { recurso: 'chi', quantidade: 2 } },
    valores: { dano: 4, impacto: 1 },
    cooldown: 2,
    texto: 'Se completar um Kata neste turno, recebe +2 D.',
  },
  {
    id: cardId('MO10'),
    classe: 'monge',
    nome: 'Varredura Final',
    tipo: 'ataque',
    tags: [],
    kata: 'finalizacao',
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 2 },
    cooldown: 2,
    texto:
      'Se completar um Kata e provocar Ruptura, seu primeiro Ataque no próximo turno recebe +1 D.',
  },
  {
    id: cardId('MO11'),
    classe: 'monge',
    nome: 'Respiração Centrada',
    tipo: 'tecnica',
    tags: [],
    kata: 'abertura',
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'Recupere até 2 Chi Gastos.',
  },
  {
    id: cardId('MO12'),
    classe: 'monge',
    nome: 'Passo sem Sombra',
    tipo: 'tecnica',
    tags: [],
    kata: 'fluxo',
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Se vier depois de Abertura, sua próxima Finalização neste turno custa 1 AP a menos, mínimo 1.',
  },
  {
    id: cardId('MO13'),
    classe: 'monge',
    nome: 'Quebrar o Ritmo',
    tipo: 'tecnica',
    tags: [],
    kata: 'abertura',
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'Seu próximo Ataque de Fluxo neste turno recebe +2 I.',
  },
  {
    id: cardId('MO14'),
    classe: 'monge',
    nome: 'Circular Energia',
    tipo: 'tecnica',
    tags: [],
    kata: 'fluxo',
    custo: { moeda: 'ap', valor: 1, recurso: { recurso: 'chi', quantidade: 1 } },
    cooldown: 2,
    texto:
      'Sua próxima Finalização recebe +1 D e +1 I. Se completar Kata, a Finalização entra em uma zona de cooldown mais próxima da mão.',
  },
  {
    id: cardId('MO15'),
    classe: 'monge',
    nome: 'Selar o Kata',
    tipo: 'tecnica',
    tags: [],
    kata: 'finalizacao',
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 3,
    texto:
      'Só depois de Fluxo. Se a Ação anterior ao Fluxo foi Abertura, complete o Kata e devolva 1 habilidade sua de CD1 à mão.',
  },
  {
    id: cardId('MO16'),
    classe: 'monge',
    nome: 'Antebraço de Pedra',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 2 D e 2 I. Se impedir Ruptura, recupere 1 Chi Gasto.',
  },
  {
    id: cardId('MO17'),
    classe: 'monge',
    nome: 'Desvio Lateral',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 3 D.',
  },
  {
    id: cardId('MO18'),
    classe: 'monge',
    nome: 'Redirecionar Força',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1, recurso: { recurso: 'chi', quantidade: 1 } },
    cooldown: 1,
    texto:
      'Reduza 3 I. Se o Impacto final se tornar 0, seu próximo Ataque de Abertura recebe +1 I.',
  },
  {
    id: cardId('MO19'),
    classe: 'monge',
    nome: 'Contra-Golpe',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2, recurso: { recurso: 'chi', quantidade: 1 } },
    cooldown: 2,
    texto: 'Reduza 2 D. Se o Dano final for 0, o adversário perde 2 Vida.',
  },
  {
    id: cardId('MO20'),
    classe: 'monge',
    nome: 'Corpo Vazio',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2, recurso: { recurso: 'chi', quantidade: 2 } },
    cooldown: 3,
    texto: 'Reduza 3 D e 3 I.',
  },
];
