import { cardId } from '@arcane-duel/shared-types';

import type { DefinicaoDeCarta } from '../card-definition.js';

/*
 * As vinte habilidades do Druida, transcritas de docs/CARD_CATALOG.md.
 *
 * A Forma não é moeda: ela é o estado em que o Druida está, e o texto lê esse
 * estado ("Na Forma Humana...", "Na Forma Selvagem..."). Mudar de Forma é
 * gratuito uma vez no início do próprio turno; fora disso, exige carta.
 */
export const HABILIDADES_DO_DRUIDA: readonly DefinicaoDeCarta[] = [
  {
    id: cardId('D01'),
    classe: 'druida',
    nome: 'Chicote de Raízes',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: 'Na Forma Humana, se for sua primeira Ação, recebe +1 I.',
  },
  {
    id: cardId('D02'),
    classe: 'druida',
    nome: 'Espinhos Vivos',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 2 },
    cooldown: 2,
    texto:
      'Na Forma Humana, se o adversário usar uma carta de Reação, recebe +1 D depois da redução.',
  },
  {
    id: cardId('D03'),
    classe: 'druida',
    nome: 'Raio da Tempestade',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 4, impacto: 1 },
    cooldown: 2,
    texto: 'Na Forma Humana, se for usado imediatamente depois de uma Técnica, recebe +1 I.',
  },
  {
    id: cardId('D04'),
    classe: 'druida',
    nome: 'Garra Selvagem',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    valores: { dano: 2, impacto: 1 },
    cooldown: 1,
    texto: 'Na Forma Selvagem, recebe +1 D.',
  },
  {
    id: cardId('D05'),
    classe: 'druida',
    nome: 'Mordida Predatória',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 4, impacto: 1 },
    cooldown: 2,
    texto:
      'Na Forma Selvagem, se o adversário estiver com 3 ou menos de Guarda ao declarar, recebe +1 D.',
  },
  {
    id: cardId('D06'),
    classe: 'druida',
    nome: 'Investida Bestial',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 3 },
    cooldown: 2,
    texto: 'Na Forma Selvagem, recebe +1 I se for sua primeira Ação ofensiva do turno.',
  },
  {
    id: cardId('D07'),
    classe: 'druida',
    nome: 'Garras Gêmeas',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 3, impacto: 1 },
    cooldown: 2,
    texto:
      'Se uma ação anterior neste turno ocorreu em Forma Humana e depois você se transformou, recebe +2 D.',
  },
  {
    id: cardId('D08'),
    classe: 'druida',
    nome: 'Golpe Totêmico',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 5, impacto: 2 },
    cooldown: 2,
    texto: 'Se mudou de forma neste turno, recebe +1 D e +1 I.',
  },
  {
    id: cardId('D09'),
    classe: 'druida',
    nome: 'Fúria da Tempestade',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 3 },
    valores: { dano: 4, impacto: 4 },
    cooldown: 3,
    texto: 'Na Forma Humana, recebe +1 I. Na Forma Selvagem, recebe +1 D.',
  },
  {
    id: cardId('D10'),
    classe: 'druida',
    nome: 'Predador da Lua',
    tipo: 'ataque',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    valores: { dano: 4, impacto: 0 },
    cooldown: 2,
    texto: 'Na Forma Selvagem, se for sua terceira Ação, recebe +2 D.',
  },
  {
    id: cardId('D11'),
    classe: 'druida',
    nome: 'Crescimento Súbito',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 1,
    texto:
      'Seu próximo Ataque neste turno recebe +1 D e +1 I. Na Forma Humana, também restaure 1 Guarda.',
  },
  {
    id: cardId('D12'),
    classe: 'druida',
    nome: 'Metamorfose Instintiva',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Mude de forma. Essa mudança não conta como a Metamorfose gratuita do início do turno. Depois, sua próxima Ação neste turno custa 1 AP a menos, mínimo 1.',
  },
  {
    id: cardId('D13'),
    classe: 'druida',
    nome: 'Renovo Natural',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 2 },
    cooldown: 2,
    texto: 'Restaure 2 Vida. Na Forma Humana, restaure 3 em vez disso.',
  },
  {
    id: cardId('D14'),
    classe: 'druida',
    nome: 'Casca de Carvalho',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto: 'Até o início do seu próximo turno, sua primeira Resposta reduz +1 D e +1 I.',
  },
  {
    id: cardId('D15'),
    classe: 'druida',
    nome: 'Lua Crescente',
    tipo: 'tecnica',
    tags: [],
    custo: { moeda: 'ap', valor: 1 },
    cooldown: 2,
    texto:
      'Se estiver Humano, transforme-se em Selvagem. Seu próximo Ataque Selvagem neste turno recebe +2 D. Se já estiver Selvagem, apenas recebe o bônus.',
  },
  {
    id: cardId('D16'),
    classe: 'druida',
    nome: 'Casca Reflexa',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 2 D e 2 I. Na Forma Humana, se impedir Ruptura, restaure 1 Guarda.',
  },
  {
    id: cardId('D17'),
    classe: 'druida',
    nome: 'Instinto Feral',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 3 D. Na Forma Selvagem, reduza 4 D em vez disso.',
  },
  {
    id: cardId('D18'),
    classe: 'druida',
    nome: 'Raízes Protetoras',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 1 },
    cooldown: 1,
    texto: 'Reduza 3 I. Na Forma Humana, se o Impacto final for 0, seu próximo Ataque recebe +1 I.',
  },
  {
    id: cardId('D19'),
    classe: 'druida',
    nome: 'Salto da Fera',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto:
      'Reduza 2 D e 2 I. Na Forma Selvagem, se o Dano final for 0, seu próximo Ataque recebe +1 D.',
  },
  {
    id: cardId('D20'),
    classe: 'druida',
    nome: 'Mudar com o Golpe',
    tipo: 'reacao',
    tags: [],
    custo: { moeda: 'reserva', valor: 2 },
    cooldown: 2,
    texto:
      'Reduza 3 D e 1 I. Depois da resolução, você pode mudar de forma. Essa mudança não consome a Metamorfose gratuita do início do seu próximo turno.',
  },
];
